### ISSUE TITLE
Need to pass Deconz Port and IP

### ISSUE THREAD

**Issue by clutwo** [MaxBec/diyHue-hassio#1]
Thanks for the addon! 
Unfortunately I cannot get it to work with my setup since I need to be able to pass in DECONZ IP address as well as the port. 
Maybe it is already possible and I have not seen it?

**Comment by MaxBec** [comment]
Hey @clutwo ,

you can enable deconz and enter the deconz port in the config.json.
In hassio it is under /config/diyhue/config.json.

```
        "deconz": {
            "enabled": false,
            "lights": {},
            "port": 8080,
            "sensors": {}
        },
```

**Comment by clutwo** [comment]
Thanks @MaxBec , will do!

**Comment by MaxBec** [comment]
Looking forward to hear from you if it is working!

**Comment by clutwo** [comment]
Sadly, it is not! I'm not able to enter the IP address, it always says 127.0.0.1 in the logs. Now, I'm using deconz as a HassIO addon as well, but I'm guessing that 127.0.0.1 refers to the docker container's ip address, which isnt't the same as the deconz ip address.

I tried entering the IP into deconz config as "ip" and "ipaddress". 
In deconz, I enabled "Authenticate app", so I can rule this out as an error source. I tried the deconz api as well as websocket port, both don't seem to work (probably because of the IP address).

Log just says "2020-12-06 12:54:38,248 - protocols.deconz.deconz - INFO - registration fail, is the link button pressed?" .

**Comment by MaxBec** [comment]
Please test the newest version and enter deconz ip in config before starting.

**Comment by clutwo** [comment]
Thank you, that worked! I still needed to enter the port number manually into the config file (as that file assumes 8080), so that would probably be another good convenience option for the addon configuration file in the future.

**Comment by MaxBec** [comment]
Will try to implement that. Thank you for the input!
