### ISSUE TITLE
Gateway in Config File wrong?

### ISSUE THREAD

**Issue by almostserious** [MaxBec/diyHue-hassio#3]
Please excuse my ignorance.. 

im currently trying to get the diyhue addon recognized by the HUE App but am failing miserably. I assume this is some VLAN reason... 

Anyway, while going through the config file, i realized that the gateway that is set is:
`172.30.33.1`
Shouldn't this actually be:
`172.30.32.1`

At least that is also what portainer and the debug log shows as being queried by the addon.
Please feel free to close this if this is completely wrong.

**Comment by MaxBec** [comment]
Hey @almostserious,

i didn't hat any problems with the IP. It should setup itself properly.
Just check the hassio Port settings. It must be port 80 and 443.


![Supervisor_-_Home_Assistant](https://user-images.githubusercontent.com/8254514/101332898-387dd880-3876-11eb-91be-5a6986b89b2c.png)

**Comment by almostserious** [comment]
Yes indeed, it was setup automatically at 448 and 88 because i already have the NGINX Proxy Manager running on 80 and 443. For testing i just disabled nginx and my HueApp was immediately able to find it. Doesnt seem possible for both addons to coexist as they both require the same ports and its not possible to change them. Any idea?
